version: 0.2

env:
  variables:
    CI: 'true'

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm i
  build:
    commands:
      - npm run lint
      - npm run build
      - npm run docs
  post_build:
    commands:
      - aws s3 sync ./.styleguidist s3://panther-pounce-distribution --recursive --acl public-read
