version: 2.1

defaults:
  docker:
    - image: circleci/node:10.16.3

commands:
  setup:
    steps:
      - run:
          name: Lint project and run TS checks
          command: npm run lint
      - run:
          name: Install js dependencies
          command: npm i

jobs:
  build:
    steps:
      - checkout
      - setup
      - run:
          name: Build the project
          command: npm run build

  docs:
    steps:
      - checkout
      - setup
      - run:
          name: Generate documentation
          command: npm run docs

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - docs
