version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12.16

commands:
  setup:
    steps:
      - checkout
      - run:
          name: Install js dependencies
          command: npm i

jobs:
  build:
    executor: node
    steps:
      - setup
      - run:
          name: Lint project and run TS checks
          command: npm run lint
      - run:
          name: Build the project
          command: npm run build

  docs:
    executor: node
    steps:
      - setup
      - run:
          name: Generate documentation pages
          command: npm run docs
      - run:
          name: Setup documentation deployment
          command: |
            sudo npm install -g surge@latest
      - run:
          name: Deploy documentation pages
          command: surge --project .styleguidist --domain pouncejs.surge.sh

  release:
    executor: node
    steps:
      - setup
      - run:
          name: Create a new release with proper changelog
          command: npx semantic-release

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - release:
          filters:
            branches:
              only: master
      - docs:
          filters:
            branches:
              only: master
