version: 2.1
executors:
  node-env:
    docker:
      - image: circleci/node:10.16.3

jobs:
  setup:
    executor:
      - name: node-env
    steps:
      - checkout
      - run: npm lint
      - run: npm i

  build:
    executor:
      - name: node-env
    steps:
      - install
      - lint
      - run: npm run build

  docs:
    executor:
      - name: node-env
    steps:
      - install
      - run: npm run docs

workflows:
  version: 2
  build:
    jobs:
      - setup
      - build
      - docs
