version: 2.1
executors:
  node-env:
    docker:
      - image: circleci/node:10.16.3

commands:
  setup:
    executor: node-env
    steps:
      - run:
          name: Lint project and run TS checks
          command: npm run lint
      - run:
          name: Install js dependencies
          command: npm i

jobs:
  build:
    executor: node-env
    steps:
      - checkout
      - setup
      - run: npm run build

  docs:
    executor: node-env
    steps:
      - checkout
      - setup
      - run: npm run docs

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - docs
