version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.16.3

commands:
  setup:
    steps:
      - run:
          name: Install js dependencies
          command: npm i
      - run:
          name: Lint project and run TS checks
          command: npm run lint

jobs:
  build:
    executor: node
    steps:
      - checkout
      - setup
      - run:
          name: Build the project
          command: npm run build

  docs:
    executor: node
    steps:
      - checkout
      - setup
      - run:
          name: Generate documentation pages
          command: npm run docs
      - run:
          name: Setup documentation deployment
          command: |
            npm install gh-pages@latest --unsafe-perm=true --allow-root
            git config user.email "github-service-account@runpanther.io"
            git config user.name "panther-service-account"
      - run:
          name: Deploy documentation pages
          command: .node_modules/gh-pages --dist .styleguidist

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - docs
#          filters:
#            branches:
#              only: master
